"""add extracted fields

Revision ID: 2d7384fc44a7
Revises: faa7b6c743a0
Create Date: 2026-09-11 04:37:04.235893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7384fc44a7'
down_revision: Union[str, Sequence[str], None] = 'faa7b6c743a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_fields', sa.JSON(), nullable=True))
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.VARCHAR(), nullable=True))
    op.drop_column('documents', 'extracted_fields')
    # ### end Alembic commands ###
